# Site settings
title: S0AndS0
email: StrangerThanBland@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Documenting technical topics and writing tools since 2013
url: 'https://s0ands0.github.io' # Required for `absolute_url` Liquid piping
author: S0AndS0
## Future dated content publish configuration
future: true


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata


## Theme settings
minima:
  social_links:
    github: S0AndS0
    youtube_channel: UCmR4BGgzj_ZrrDIR0A0uSEg
    youtube_channel_name: Various Video Guides
    twitter: S0_And_S0


sass:
  load_paths:
    - _sass
    - _scss


## Collections settings
# collections_dir: projects
# collections:
#   some_project:
#     output: true
#     permalink: /:collection/:name/


# Exclude from processing.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
