# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: S0AndS0
description: >- # this means to ignore newlines until "baseurl:"
  Miscellaneous tips, tricks, and thoughts from the author known as S0AndS0
# baseurl: "" # the subpath of your site, e.g. /blog
url: 'https://s0ands0.github.io'
author: S0AndS0
twitter_username: S0_And_S0

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata


# minima:
#   social_links:
#     twitter: S0_And_S0


## Thanks be to - https://jekyllrb.com/docs/collections/
collections_dir: misc
collections:
  awk:
    output: true
    permalink: /:collection/:name/
  bash:
    output: true
    permalink: /:collection/:name/
  css:
    output: true
    permalink: /:collection/:name/
  gha:
    output: true
    permalink: /:collection/:name/
  git:
    output: true
    permalink: /:collection/:name/
  javascript:
    output: true
    permalink: /:collection/:name/
  projects:
    output: true
    permalink: /:collection/:name/
  python:
    output: true
    permalink: /:collection/:name/
  rust:
    output: true
    permalink: /:collection/:name/
  scripting:
    output: true
    permalink: /:collection/:name/
  vim:
    output: true
    permalink: /:collection/:name/

##
attribution:
  title: Attribution
  class_prefix: attribution
  auto_font_awesome: true

include:
  - .github/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
