
on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cache assets/images
        uses: actions/cache@v4
        id: cache-images-cooking
        with:
          key: cache-images-cooking
          path: assets/images/cooking

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: true
          ref: ${{ github.head_ref }}
          submodules: 'recursive'

      - name: Convert and half-size images with ImageMagick -- Cooking
        uses: gha-utilities/ImageMagick@v0.0.5
        with:
          source_directory: assets/images/cooking
          find_regex: '.*[0-9]+[a-z-]+.jpg'
          destination_extensions: png,avif
          magick_opts: "-resize '50%'"
          destination_name_suffix: '_50-percent'

      - name: Convert and quarter-size images with ImageMagick -- Cooking
        uses: gha-utilities/ImageMagick@v0.0.5
        with:
          source_directory: assets/images/cooking
          find_regex: '.*[0-9]+[a-z-]+.jpg'
          destination_extensions: png,avif
          magick_opts: "-resize '25%'"
          destination_name_suffix: '_25-percent'

      # ↓ Do some site building here ↓
      - name: Setup pages
        uses: actions/configure-pages@v5.0.0
      - name: Build pages
        uses: actions/jekyll-build-pages@v1
      # ↑ Do some site building here ↑

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
